IIIF Collection search handler
nulib/dc-api-v2 pull request #19
Opened 2022-09-02 16:14 UTC by kdid

2022-09-02 20:47 UTC, mbklein requested changes

2022-09-02 20:47 UTC, mbklein commented on src/api/response/iiif/collection.js
> +  );
JavaScript has a great built-in [`URL`](https://nodejs.org/docs/latest-v16.x/api/url.html) class that can automatically handle URL path joining and query encoding (and a lot of other things) that's far more reliable than string concatenation:
  - `new URL(relativePath, base)` resolves the full URL and accounts for the fact that the base may or may not have a trailing slash
  - The `URL` class' `searchParams` property has `get`/`set` methods that act on the query part of the URL directly and handle encoding/decoding for you
  - `searchParams` also handles `"` escaping automatically, so the `.replace(/\"/g, '\\"')` can probably go away (unless I'm wrong about what you're trying to do there).
  - An instance of the `URL` class will automatically be stringified when interpolated or converted to JSON, so you don't even need to call `.toString()` on it yourself.

That would leave:
```
const result = new URL("/search", dcUrl);
result.searchParams.set("q", pageInfo.options.queryString);
return result;
```

2022-09-02 20:48 UTC, mbklein commented on src/api/response/iiif/collection.js
> +  );
I used this as the most obvious example, but I think there are a few places in the IIIF code where you have to construct URLs, and I think using the `URL` class provides a bit of a formatting and encoding safety net.

2022-09-02 20:54 UTC, mbklein commented
There's one other issue that predates this PR, but I was able to trigger it by hitting `GET /search` with no query string:
```
$ curl http://localhost:3000/search                                                                          
{"message":"Cannot read properties of undefined (reading 'searchToken')"}%
```

When there are no query string parameters, `event.queryStringParameters` is undefined. So I think every instance of `event.queryStringParameters.whatever` needs to be replaced with `event.queryStringParameters?.whatever` to avoid the error.

2022-09-06 20:09 UTC, mbklein approved these changes

2022-09-06 20:28 UTC, bmquinn approved these changes

2022-09-06 20:29 UTC, merged