Add ?as=iiif param to top level collections endpoint.
nulib/dc-api-v2 pull request #232
Opened 2024-07-22 19:16 UTC by mathewjordan

2024-07-23 21:27 UTC, mbklein commented
This looks great. The only thing missing is an update to the [OpenAPI spec](https://github.com/nulib/dc-api-v2/blob/deploy/staging/docs/docs/spec/openapi.yaml) – the `/collections` route spec needs a reference to the `as` param (which you can just copy/paste from the `/collections/{id}` route spec).

I don't think there's anything to update in the docs regarding the Presentation API stuff because we pretty much punted and called all document responses `object` types.

2024-07-23 21:28 UTC, mbklein requested changes
This looks great. The only thing missing is an update to the [OpenAPI spec](https://github.com/nulib/dc-api-v2/blob/deploy/staging/docs/docs/spec/openapi.yaml) – the `/collections` route spec needs a reference to the `as` param (which you can just copy/paste from the `/collections/{id}` route spec).

I don't think there's anything to update in the docs regarding the Presentation API stuff because we pretty much punted and called all document responses `object` types.

2024-07-23 22:21 UTC, kdid approved these changes
Looks good. Collections search route (`/search/collections?as=iiif`) working as expected as well with POST body.

2024-07-23 22:39 UTC, mathewjordan commented
> This looks great. The only thing missing is an update to the [OpenAPI spec](https://github.com/nulib/dc-api-v2/blob/deploy/staging/docs/docs/spec/openapi.yaml) – the `/collections` route spec needs a reference to the `as` param (which you can just copy/paste from the `/collections/{id}` route spec).
> 
> I don't think there's anything to update in the docs regarding the Presentation API stuff because we pretty much punted and called all document responses `object` types.

Thanks, update the spec!

2024-07-24 13:28 UTC, mbklein approved these changes

2024-07-24 13:35 UTC, merged