Add file set authorization routes
nulib/dc-api-v2 pull request #46
Opened 2022-11-04 14:39 UTC by kdid

- `/file-sets/{id}/authorization` returns `204` if file set image is authorized according to our logic and `403` if not

2022-11-04 18:17 UTC, mbklein requested changes

2022-11-04 18:17 UTC, mbklein commented on src/handlers/get-file-set-auth.js
> +      isValidToken(token);
Missing the `return` keyword.
```suggestion
      return isValidToken(token);
```

2022-11-04 18:17 UTC, mbklein commented on template.yaml
> +      Description: Authorizes access to a file set.
`API_TOKEN_SECRET` isn't part of the default set of environment variable every function gets, so in order to decode the user token, this function needs
```suggestion
      Description: Authorizes access to a file set.
      Environment:
        Variables:
          API_TOKEN_SECRET: !Ref ApiSecret
```

2022-11-04 18:30 UTC, kdid commented on package.json
> +    "lodash.isobject": "^3.0.2"
Right. Totally forgot. Will fix

2022-11-04 18:30 UTC, kdid commented on src/handlers/get-file-set-auth.js
> +      isValidToken(token);
Always forget the return in JS

2022-11-04 18:38 UTC, mbklein commented on src/handlers/get-file-set-auth.js
> +      isValidToken(token);
Same. Ruby and Elixir have ruined us. 😄

2022-11-07 15:07 UTC, mbklein approved these changes

2022-11-07 15:10 UTC, merged